language: go

go:
    - 1.4
    - 1.5
    - 1.6
    - 1.7
    - tip

#go_import_path: github.com/targodan/ffgopeg
go_import_path: gopkg.in/targodan/ffgopeg.v1

sudo: required

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libavutil-dev libswresample-dev libswscale-dev

install:
    - go get -t -v ./...

script:
    - go build -v
    - go test -v -cover -race ./...
