language: go

go:
    - 1.4
    - 1.5
    - 1.6
    - 1.7
    - tip

# On develop branch
#go_import_path: github.com/targodan/ffgopeg
# On master branch
go_import_path: gopkg.in/targodan/ffgopeg.v1

# Possible dependencies:
# yasm(?), pkg-config(?)

before_install:
    - pushd /tmp
    - wget https://www.targodan.de/downloads/builds/ffmpeg-3.1.4_x86_64-precise-pangolin.tar.gz
    - tar -xf ffmpeg-3.1.4_x86_64-precise-pangolin.tar.gz
    - cd ffmpeg-3.1.4/
    - make install
    - popd

install:
    - go get -t -v ./...

script:
    - go build -v
    - go test -v -cover -race ./...
